#!/usr/bin/env python3
import json
from datetime import datetime

# Official Latvian name days (varda dienas) from Valsts valodas centrs (VVC)
NAMEDAYS = [
  [  # Month 1 (31 days)
    "Laimnesis, Solvita, Solvija",
    "Indulis, Ivo, Iva, Ivis",
    "Miervaldis, Miervalda, Ringolds",
    "Spodra, Ilva, Ilvita",
    "S\u012bmanis, Zintis",
    "Spulga, Arnita",
    "Rota, Zigm\u0101rs, Juli\u0101ns, Digm\u0101rs",
    "Gatis, Ivanda",
    "Kaspars, Aksels, Alta",
    "Tatjana, Dorisa",
    "Smaida, Franciska",
    "Reinis, Reina, Reinholds, Ren\u0101ts",
    "Harijs, \u0100rijs, \u0100ris, Aira",
    "Roberts, Roberta, Raitis, Raits",
    "F\u0113likss, Felicita",
    "Lidija, Lida",
    "Tenis, Dravis",
    "Antons, Antis, Antonijs",
    "Andulis, Alnis",
    "O\u013c\u0123erts, Orests, A\u013c\u0123irds, A\u013c\u0123is",
    "Agnese, Agnija, Agne",
    "Austris",
    "Grieta, Strauta, Rebeka",
    "Kri\u0161s, Ksenija, Eglons, Egle",
    "Zigurds, Sigurds, Sigvards",
    "Ansis, Agnis, Agneta",
    "Ilze, Ildze, Izolde",
    "K\u0101rlis, Spodris",
    "Aivars, Val\u0113rijs, Bille",
    "T\u012bna, Valent\u012bna, P\u0101rsla",
    "Tekla, Violeta",
  ],
  [  # Month 2 (28 days)
    "Brigita, Indra, Indars, Indris",
    "Sp\u012bdola, Sonora",
    "A\u012bda, Ida, Vida",
    "Daila, Veronika, Dominiks",
    "Agate, Selga, Silga, Sinilga",
    "Dace, D\u0101rta, Dora, Daris",
    "Nelda, Rihards, Ri\u010dards, Ri\u0161ards",
    "Aldona, \u010ceslavs",
    "Simona, Apolonija",
    "Paul\u012bne, Paula, Jasm\u012bna",
    "Laima, Laimdota",
    "Karl\u012bna, L\u012bna",
    "Malda, Melita",
    "Valent\u012bns",
    "Alvils, Olafs, Aloizs, Olavs",
    "J\u016blija, D\u017euljeta",
    "Donats, Konstance",
    "Kora, Kintija",
    "Zane, Zuzanna",
    "Vitauts, Smuidra, Smuidris",
    "Eleonora, Ariadne",
    "\u0100rija, Rigonda, Adrians, Adri\u0101na, Adrija",
    "Haralds, Almants",
    "Di\u0101na, Dina, Dins",
    "Alma, Annemarija",
    "Evel\u012bna, Aur\u0113lija, M\u0113tra",
    "L\u012bvija, L\u012bva, Andra",
    "Skaidr\u012bte, Justs, Skaidra",
  ],
  [  # Month 3 (31 days)
    "Ivars, Ilgvars",
    "Lav\u012bze, Lu\u012bze, Laila",
    "T\u0101lis, T\u0101lavs, Marts",
    "Alise, Auce, Enija",
    "Austra, Aurora, Aurika",
    "Vents, Centis, Gotfr\u012bds",
    "Ella, Elm\u012bra",
    "Dagm\u0101ra, Marga, Margita",
    "\u0112valds",
    "Silvija, Laimrota, Lili\u0101na",
    "Konstant\u012bns, Agita",
    "Aija, Aiva, Aivis",
    "Ernests, Balvis",
    "Matilde, Ulrika",
    "Amilda, Amalda, Imalda",
    "Guntis, Guntars, Guntris",
    "\u0122ertr\u016bde, Gerda, Gerhards",
    "Ilona, Adel\u012bna",
    "J\u0101zeps, Juzefa",
    "Made, Irbe",
    "Una, Unigunde, Dzelme, Benedikts, Benedikta",
    "Tam\u0101ra, Dziedra, Gabriels, Gabriela",
    "Mirdza, \u017danete, \u017danna",
    "Kazimirs, Izidors",
    "M\u0101ra, M\u0101r\u012bte, Marita, Mare, \u0122edimins",
    "Ei\u017eenija, \u017denija",
    "Gustavs, Gusts, T\u0101lr\u012bts, Saulis",
    "Gunta, Ginta, Gunda",
    "Aldonis, Agija",
    "Nanija, Ilgm\u0101rs",
    "Gvido, Atvars",
  ],
  [  # Month 4 (30 days)
    "Dagnis, Dagne",
    "Irmgarde",
    "Daira, Dairis, Daiva, Daivis",
    "Valda, Herta, \u0100rvalda, \u0100rvalds, \u0100rvaldis",
    "Vija, Vidaga, Aivija",
    "Zinta, V\u012blips, Filips, Dzinta, Dzintis",
    "Zina, Zina\u012bda, Helmuts",
    "Edgars, Danute, Dana, Dans",
    "Val\u0113rija, \u017dub\u012bte, Alla",
    "Anita, Anitra, Z\u012ble, Annika",
    "Hermanis, Vilm\u0101rs",
    "J\u016blijs, Ainis",
    "Egils, Eg\u012bls, Nauris",
    "Strauja, Gudr\u012bte",
    "Aelita, Gastons",
    "Mintauts, Alfs, Bernadeta",
    "R\u016bdolfs, Vivi\u0101na, R\u016bdis",
    "Laura, Jadviga",
    "V\u0113sma, Fanija",
    "Mirta, Zied\u012bte, Meija",
    "Mar\u0123ers, Anastasija",
    "Armands, Armanda",
    "Jur\u0123is, Juris, Georgs, Jurgita",
    "Visvaldis, Nameda, Ritvaldis, Ritums",
    "L\u012bksma, B\u0101rbala",
    "Al\u012bna, Sandris, R\u016bsi\u0146\u0161",
    "T\u0101le, Raimonda, Raina, Klement\u012bne",
    "Gundega, Ter\u0113ze",
    "Vilnis, Raimonds, Laine",
    "Lilija, Li\u0101na",
  ],
  [  # Month 5 (31 days)
    "Ziedonis",
    "Zigmunds, Sigmunds, Zigismunds",
    "Gints, Uvis",
    "Vizbul\u012bte, Viola, Vijol\u012bte",
    "\u0122irts, \u0122ederts",
    "Gaidis, Didzis",
    "Henriete, Henrijs, Jete, Enriko",
    "Sta\u0146islavs, Sta\u0146islava, Stef\u0101nija",
    "Kl\u0101vs, Ein\u0101rs, Erv\u012bns",
    "Maija, Paija",
    "Milda, Karmena, Manfreds",
    "Valija, In\u0101ra, Ina, In\u0101rs",
    "Ir\u0113na, Ir\u012bna, Ira, Ira\u012bda",
    "Kri\u0161j\u0101nis, Elfa, Aivita, Elvita",
    "Sofija, Taiga, Airita, Arita",
    "Edv\u012bns, Edijs",
    "Herberts, Dailis, Umberts",
    "Inese, Inesis, \u0112riks",
    "Lita, Sibilla, Teika",
    "Venta, Salvis, Selva",
    "Ernest\u012bne, Ingm\u0101rs, Akvel\u012bna",
    "Em\u012blija. Visu neparasto un kalend\u0101ros neierakst\u012bto v\u0101rdu diena",
    "Leont\u012bne, Leok\u0101dija, Lonija, Ligija",
    "Ilvija, Marl\u0113na, Ziedone",
    "An\u0161lavs, Junora",
    "Edvards, Edvarts, Eduards, Varis",
    "Dzidra, Gunita, Loreta, Dzidris",
    "Vilis, Vilhelms",
    "Maksis, Maksims, Raivis, Raivo",
    "Vitolds, Lolita, Let\u012bcija",
    "Al\u012bda, J\u016bsma",
  ],
  [  # Month 6 (30 days)
    "Biruta, Mairita, Berned\u012bne",
    "L\u012bba, Emma",
    "Inta, Ineta, Intra",
    "Elfr\u012bda, Sintija, Sindija",
    "Igors, Margots, Ingvars",
    "Ingr\u012bda, Ardis",
    "Gaida, Arnis, Arno",
    "Fr\u012bdis, Fr\u012bda, Mundra",
    "Ligita, Gita",
    "Malva, Anatols, Anatolijs",
    "Ingus, Mairis, Vidvuds",
    "Nora, Lenora, Ija",
    "Zigfr\u012bds, Ain\u0101rs, Uva",
    "Tija, Saiva, Sentis, Santis, Saivis",
    "Ba\u0146uta, \u017derm\u0113na, Vilija, Vits",
    "Just\u012bne, Juta",
    "Art\u016brs, Artis",
    "Alberts, Madis",
    "Viktors, Nils",
    "Rasma, Rasa, Maira",
    "Em\u012bls, Egita, Monv\u012bds",
    "Ludmila, Laimdots, Laimi\u0146\u0161",
    "L\u012bga",
    "J\u0101nis",
    "Milija, Maiga",
    "Ausma, Inguna, Ing\u016bna, Inguns, Ausmis",
    "Malv\u012bne, Malvis",
    "Viesturs, Kitija, Viestards",
    "P\u0113teris, P\u0101vils, Pauls, Paulis",
    "T\u0101livaldis, Mareks",
  ],
  [  # Month 7 (31 days)
    "Imants, Rimants, Ingars, Intars",
    "Lauma, Ilvars, Halina",
    "Benita, Everita, Verita, Emerita",
    "Ulvis, Uldis, Sandis, Sandijs",
    "And\u017es, And\u017eejs, Ed\u012bte, Esmeralda",
    "Anrijs, Ark\u0101dijs",
    "Alda, Maruta",
    "Antra, Adele, Ada",
    "Zaiga, Asne, Asna",
    "Lija, Ol\u012bvija, Olivers, Odrija",
    "Leonora, Svens",
    "Indri\u0137is, Ints, Namejs",
    "Margrieta, Margarita",
    "Oskars, Ritvars, Anvars",
    "Egons, Egmonts, Egija, Henriks, Heinrihs",
    "Herm\u012bne, Estere, Liepa",
    "Aleksis, Aleksejs, Alekss",
    "Roz\u0101lija, Roze",
    "Jautr\u012bte, Kamila, Digna, S\u0101ra",
    "Ritma, Ramona",
    "Meldra, Meldris, Melisa",
    "Marija, Marika, Marina",
    "Magda, Magone, M\u0113rija, Magdal\u0113na",
    "Krist\u012bne, Krist\u012bna, Krista, Kristi\u0101na, Kristi\u0101ns",
    "J\u0113kabs, \u017dakl\u012bna",
    "Anna, Ance, Annija",
    "Marta, Dita, Dite",
    "Cec\u012blija, Cilda",
    "Edmunds, Ed\u017eus, Vidmants",
    "Valters, Ren\u0101rs, Regn\u0101rs",
    "R\u016bta, Ruta, Angelika, Sigita",
  ],
  [  # Month 8 (31 days)
    "Alb\u012bns, Alb\u012bna",
    "Normunds, Stefans",
    "Augusts",
    "Rom\u0101ns, Romualds, Romualda",
    "Osvalds, Arvils",
    "Askolds, Aisma",
    "Alfr\u0113ds, Madars, Fredis",
    "Mud\u012bte, Vladislavs, Vladislava",
    "Madara, Genoveva, Genovefa",
    "Brencis, Audris, Inuta, Audra",
    "Olga, Zita, Liega, Zigita",
    "Vizma, Kl\u0101ra",
    "Elv\u012bra, Velga, R\u0113zija",
    "Zelma, Zemgus, Virma",
    "Zenta, Dzelde, Zelda",
    "Astra, Astr\u012bda",
    "Vineta, O\u013cegs",
    "Liene, Hel\u0113na, Elena, Ellena, Liena",
    "Mel\u0101nija, Imanta",
    "Bernhards, Boriss, Rojs",
    "Jan\u012bna, Linda",
    "Rud\u012bte, Everts",
    "Vit\u0101lijs, Ralfs, Valgudis",
    "B\u0113rtulis, Bo\u013ceslavs",
    "Ludvigs, Ludis, Ivonna, Patr\u012bcija, Patriks",
    "Nat\u0101lija, T\u0101lija, Bro\u0146islavs, Bro\u0146islava",
    "\u017danis, Jorens, Alens",
    "Auguste, Guste",
    "Arm\u012bns, Vismants, Aiga",
    "Alvis, Jolanta, Samanta",
    "Vilma, Aigars",
  ],
  [  # Month 9 (30 days)
    "Ilm\u0101rs, Iluta, Austrums",
    "El\u012bza, Lizete, Zete",
    "Berta, Bella",
    "Dzintra, Dzintara, Dzintars",
    "Klaudija, Persijs, Vaida",
    "Maigonis, Magnuss, Mariuss",
    "Reg\u012bna, Erm\u012bns",
    "Ilga",
    "Bruno, Telma",
    "Jausma, Albert\u012bne",
    "Signe, Signija",
    "Erna, Evita, Eva",
    "Iza, Izabella",
    "Sanita, Santa, Sanda, Sanija, Sandija",
    "Sandra, Gunvaldis, Gunvaris, Sondra",
    "Asja, Asnate, D\u0101gs",
    "Vera, Vaira, Vairis, Vaiva",
    "Liesma, Elita, Alita",
    "Verners, Muntis",
    "Guntra, Ginters, Marianna",
    "Modris, Mat\u012bss, Mariss",
    "M\u0101ris, M\u0101rica, Maigurs",
    "Vanda, Veneranda, Venija",
    "Agris, Agrita",
    "Rodrigo, Rauls",
    "Gundars, Kurts, Knuts",
    "\u0100dolfs, Ilgonis",
    "Sergejs, Svetlana, Lana",
    "Mi\u0137elis, Mikus, Miks, Mihails, Jumis",
    "Elma, Menarda, Elna",
  ],
  [  # Month 10 (31 days)
    "Zanda, L\u0101sma, Zandis",
    "Ilma, Skaidris",
    "Elza, Ilizana",
    "Modra, Francis, Dmitrijs",
    "Am\u0101lija, Am\u0113lija",
    "Monika, Zilgma, Zilga",
    "Daumants, Druvvaldis",
    "Aina, Anete",
    "Elga, Helga, Elgars",
    "Arv\u012bds, Arvis, Druvis",
    "Monta, Tince, Silva",
    "Valfr\u012bds, Kira",
    "Irma, Mirga",
    "Vilhelm\u012bne, Minna",
    "Eda, Hedviga, Helvijs",
    "Daiga, Dinija, Din\u0101rs",
    "Gaits, Kar\u012bna, Gaitis",
    "Rolands, Rolanda, Ronalds, Erlends, L\u016bkass",
    "El\u012bna, Drosma, Drosmis",
    "Leon\u012bds, Leon\u012bda",
    "Urzula, Sever\u012bns",
    "\u012arisa, Ir\u012bda, Airisa",
    "Daina, Dainis, Dainida",
    "Ren\u0101te, Modr\u012bte, Mudr\u012bte",
    "Be\u0101te, Beatrise",
    "Amanda, Kaiva, Amanta",
    "Lilita, Irita, Ita",
    "\u0145ina, Ninona, Anto\u0146ina, Oksana",
    "Laimonis, Elvijs, Elva, Elvis, Laimis",
    "Nad\u012bna, Ulla, Ad\u012bna",
    "Valts, Rinalds, Rinalda",
  ],
  [  # Month 11 (30 days)
    "Ikars",
    "Vivita, Dz\u012ble, Viva",
    "\u0112rika, Dagnija",
    "Atis, Otom\u0101rs, Oto",
    "\u0160arlote, Lote",
    "Linards, Leons, Leo, Leonards, Leonarda",
    "Helma, Lot\u0101rs, P\u0113rle",
    "Aleksandra, Agra",
    "Teodors",
    "M\u0101rti\u0146\u0161, M\u0101rcis, Markuss, Marks",
    "Oj\u0101rs, Rainers, Nellija",
    "Kaija, Korn\u0113lija",
    "Ei\u017eens, Jevge\u0146ijs, Jevge\u0146ija",
    "Fricis, Vikentijs, Vincents",
    "Leopolds, Und\u012bne, Unda",
    "Banga, Glorija",
    "Hugo, Uga, U\u0123is",
    "Aleksandrs, Doloresa, Br\u012bve",
    "Elizabete, Liza, L\u012bze, Betija",
    "Anda, And\u012bna, Vigo",
    "Zelt\u012bte, Andis",
    "Aldis, Alfons, Aldris",
    "Zigr\u012bda, Zigfr\u012bda, Zigr\u012bds",
    "Velta, Velda",
    "Katr\u012bna, Kate, Kadrija, Tr\u012bne, Katr\u012bne",
    "Konr\u0101ds, Sebastians",
    "Lauris, Norberts",
    "Rita, Vita, Olita",
    "Ignats, Virg\u012bnija",
    "Andrievs, Andrejs, Andris",
  ],
  [  # Month 12 (31 days)
    "Arnolds, Emanuels",
    "Meta, Sniedze",
    "Evija, Raita, Jogita, Ako",
    "Baiba, Barbara, Barba",
    "Sab\u012bne, Sarma, Klaudijs",
    "Nikolajs, Nikl\u0101vs, Niks, Nikola",
    "Antonija, Anta, Dzirkst\u012bte",
    "Gun\u0101rs, Vladimirs, Gunis",
    "Tabita, Sarm\u012bte",
    "Guna, Jud\u012bte",
    "Voldem\u0101rs, Valdem\u0101rs, Valdis",
    "Ot\u012blija, Iveta",
    "L\u016bcija, Veldze",
    "Auseklis, Gaisma",
    "Johanna, Hanna, Jana",
    "Alv\u012bne",
    "Hilda, Teiksma",
    "Kristaps, Kristofers, Krists, Klinta, Kristers",
    "Lelde, Sarmis",
    "Arta, Minjona",
    "Toms, Tomass, Saulcer\u012bte",
    "Saulvedis, Saule",
    "Viktorija, Balva",
    "\u0100dams, Ieva",
    "Stella, Larisa",
    "Dainuv\u012bte, Gija, Megija",
    "Elm\u0101rs, Inita, Helm\u0101rs",
    "Inga, Ivita, Irvita, Ingeborga",
    "Solveiga, Ilgona",
    "D\u0101vids, D\u0101vis, D\u0101niels, Daniela, Daniels",
    "Silvestrs, Silvis, Kalvis",
  ],
]


def main():
    now = datetime.now()
    month, day = now.month, now.day
    try:
        names = NAMEDAYS[month - 1][day - 1]
    except IndexError:
        names = "—"

    date_str = now.strftime("%H:%M   %Y.%m.%d")
    tooltip = names
    alt = now.strftime("%Y.%m.%d")

    print(json.dumps({
        "text": date_str,
        "alt": alt,
        "tooltip": tooltip,
        "class": "namedays",
    }))


if __name__ == "__main__":
    main()
