# enable mouse
set -g mouse on

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'egel/tmux-gruvbox'

set -g @tmux-gruvbox 'dark-transparent'

bind-key g popup -E -w 80% -h 80% -x C -y C -d "#{pane_current_path}" lazygit
bind-key h popup -E -w 80% -h 80% -x C -y C -d "#{pane_current_path}" gemini
bind-key j popup -E -w 80% -h 80% -x C -y C -d "#{pane_current_path}" cursor-agent

set -g default-shell /usr/bin/fish

set -g base-index 1
setw -g pane-base-index 1

# set-option -g status-position top

run '~/.config/tmux/plugins/tpm/tpm'
