# Config variable
$terminal = ghostty
$browser = zen-browser
$fileManager = nautilus
$menu = rofi -show drun
$keyring = /usr/bin/gnome-keyring-daemon --start --components=secrets,pkcs11,ssh,gpg


# Environment variables
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct
env = ADW_DISABLE_PORTAL,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = GNOME_KEYRING_CONTROL, $($keyring)
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_QPA_PLATFORM,wayland
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = GDK_BACKEND,wayland
env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_DRM_NO_ATOMIC,1
env = LIBVA_DRIVER_NAME,iHD
env = GBM_BACKEND,i915
env = __GL_SHADER_DISK_CACHE,1
env = __GL_SHADER_DISK_CACHE_PATH,/tmp/shaders
env = __GL_SHADER_DISK_CACHE_SKIP_CLEANUP,1
# env = SSH_AUTH_SOCK, "$keyring"
# env = GPG_AGENT_INFO, "$keyring"ss
env = QT_QPA_PLATFORM,xcb
env = HYPRSHOT_DIR, $HOME/Pictures/Screenshots

# Autostart
exec-once = hyprpaper
exec-once = ~/.config/hypr/scripts/wallpaper_restore.sh    # Restore wallpaper on startup
exec-once = nm-applet
exec-once = blueman-applet
exec-once = waybar
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = hyprcursor

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-paste --type video/mp4 --watch cliphist store

exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec-once = ~/.config/hypr/scripts/kbd_monitor.sh start    # Keyboard backlight monitor

# exec = $keyring

monitor=,preferred,auto,1

source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/windowrules.conf


# Special workspace for terminal
workspace = special:terminal, on-created-empty:ghostty -e tmux new-session -A -s 


# Input
input {
    kb_layout = lv
    kb_variant = apostrophe
    kb_model = thinkpad
    kb_options =
    kb_rules =
    repeat_rate = 50
    repeat_delay = 300
    follow_mouse = true
    sensitivity = 0
    numlock_by_default = true
    force_no_accel = true
    float_switch_override_focus = 2

    touchpad {
        natural_scroll = false
        disable_while_typing = true
        tap-to-click = true
        drag_lock = true
        scroll_factor = 1.0
    }
}

device {
    name = tpps/2-ibm-trackpoint
    sensitivity = -0.5
    accel_profile = flat
}

device {
    name = synaptics-tm2964-001
    sensitivity = 0.5
    accel_profile = flat
}

# device {
#     name = thinkpad-extra-buttons
# }


# Visual
general {
    gaps_in = 3
    gaps_out = 6
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    resize_on_border = false
    allow_tearing = false
    layout = master
}

decoration {
    rounding = 4
    active_opacity = 0.97
    inactive_opacity = 0.8

    shadow {
        enabled = true
        range = 4
        render_power = 4
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 5
        passes = 1
        vibrancy = 0.1696
    }
}

animations {
    enabled = false
}


# Layout specific
master {
    new_status = master
}

dwindle {
    pseudotile = true
    preserve_split = true
}


# Misc
misc {
    disable_splash_rendering = true
    disable_hyprland_logo = true
    middle_click_paste = false
}

# Power management for ThinkPad
# exec-once = tlp start
# exec-once = tlp-stat -s
# exec-once = systemctl --user start tlp.service

exec-once = signal-desktop --password-store="gnome-libsecret"
exec-once = enpass
