windowrule = float, class:blueman-manager
windowrule = pin, class:blueman-manager
windowrule = size 500 500, class:blueman-manager
windowrule = center, class:blueman-manager

windowrule = workspace 1, class:zen
