windowrulev2 = workspace 1, class:^(ghostty)$
windowrulev2 = workspace 3, class:^(signal-desktop)$
windowrulev2 = workspace 4, class:^(zen-browser)$
windowrulev2 = workspace 4, class:^(Cursor)$
windowrulev2 = center, class:^(enpass)$, title:^(Enpass)$
windowrulev2 = float, class:^(enpass)$, title:^(Enpass)$
windowrulev2 = stayfocused, class:^(enpass)$, title:^(Enpass)$
windowrulev2 = noborder, class:^(enpass)$, title:^(Enpass)$
