windowrule {
	name = Bluetooth Manager
	match:class = blueman-manager
	float = on
	pin = on
	center = on
	size = 500 500
}

windowrule {
	name = Enpass
	match:class = Enpass
	float = on
	pin = on
	center = on
	size = 768 480
}

